# Generated by Django 5.2.3 on 2025-06-13 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('product_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities_from', to='catalog.product')),
                ('product_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities_to', to='catalog.product')),
            ],
            options={
                'unique_together': {('product_a', 'product_b')},
            },
        ),
    ]
