# Generated by Django 5.2.3 on 2025-06-13 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productsimilarity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsimilarity',
            old_name='similarity_score',
            new_name='score',
        ),
    ]
